- hosts: webservers
  become: True
  tasks:
   - name: Deploy static website 
     copy: 
       src: /var/lib/jenkins/workspace/build_job/webapp/target/webapp.war  
       dest: /opt/apache-tomcat-8.5.75/webapps
 
